layout_spectrum: 0.4851064
typography_spectrum: 0.5276596
color:
  lightness: 0.5741251
  brandStrength: 0.4077355
  saturation: 0.336443
  rhythmicContrast: 0.7847691
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Malakhi
