name: Malakhi
favicon: null
layout_spectrum: 0.4851064
typography_spectrum: 0.5276596
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71138804-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4077355
  lightness: 0.5741251
  saturation: 0.336443
  rhythmicContrast: 0.7847691
purpose: []
